@RUTE_API = http://localhost:3000 
### START Products

GET {{ RUTE_API }}/api/back/product/get/COD000003

GET {{ RUTE_API }}/api/back/product/get/COD000002

GET {{ RUTE_API }}/api/back/product/get/COD000001

### END Products


### START TEST
POST {{ RUTE_API }}/api/back/file/remove
Content-Type: application/json

{
    "idFile" : "60bcffe6ee51601daf2461e2" ,
    "code" : "COD000003"
}

###  END TEST



### START CATEGORY
POST {{ RUTE_API }}/api/back/category/remove
Content-Type: application/json

{
    "id" : "6052b642ac225569e597ccb9"
}

### END CATEGORY


### START CATEGORY
POST {{ RUTE_API }}/api/back/category/add
Content-Type: application/json

{
    "name"  : "Almacenamiento" ,
    "parent" : "6052b642ac225569e597ccb9"
}

### END CATEGORY
